[package]
name = "h3c-magic-telnet"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true

[dependencies]
md5 = "0.8"
minreq = "2"
netroute = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
